### PR TITLE
Update Server Translation to Spanish

### PR DESCRIPTION
**Pull request by ChargerMc**
Hello! its me! ;D

### CODE REVIEW

**Comment by Tornaco** [comment]
Thanks for the job!
This translation file is used for default language(English).
So we need to create a new value dir: ```value-es``` for it:
the new path should be:
``` app/src/main/res/values-es/strings.xml```
💯

**Comment by ChargerMc** [comment]
I'm so sorry my fail 😔

**Comment by Tornaco** [comment]
I have created that file in values-es/string.xml
So please help translate that one again!!!

**Comment by ChargerMc** [comment]
Done!!

**Comment by Tornaco** [comment]
Good job buddy 👍

**Pull request closed without merging**
